### PR TITLE
RegexSupport

### PR DESCRIPTION
**Pull request by AnushaBoggarapu**
RegexSupport

### CODE REVIEW

**Comment by AnushaBoggarapu** [comment]
This PR is to extract the cell names displayed in the polystat using the regex provided

**Comment by AnushaBoggarapu** [comment]
It also has fix for https://github.com/grafana/grafana-polystat-panel/issues/183

**Comment by briangann** [comment]
let me know when this is ready for review

**Comment by briangann** [comment]
I'm not sure what this is implementing. It seems to use the query "ID" for comparison/match against the regex, and alters the alias.

What is the intended use for this option?

Do you have a sample set of data I can use to test against?

**Comment by briangann** [comment]
This is what I can tell it is doing:

Checks all series "name" against a group capture regex, and replaces the name with the group value.

For 3 Queries, returning a series (and current selected)

Foo-A, values 1,2,3
Bar-B, values 4,5,6
Misc, values 7,8,9

image


Adding this regex pattern:  `/(Foo|Bar)/`

Causes the display to be:
image

**Comment by AnushaBoggarapu** [comment]
Yes we extract a part of the alias\series name using the regex. This way we can just display data of interest.

**Pull request merged**
