### PR TITLE
Fixes for issues #56, #57, #58, #63, #65 + new feature for issue #55

### PR DESCRIPTION
**Pull request by w4rgrum**
- #56 [Bug] Legends and Values are not clickable
Replaced on click method by conditional <a> tag and removed pointer events from text to avoid selection. Now tiles with click through link are clickable as a standard link.

- #55 [FR] Adding "Open in new tab" functionality for the clickThroughUrl setting
Added toggle button (in the default, overrides and composites options panels) updating the target to blank/self on the tiles links

- #58 Multiple variables cannot be passed into clickThrough url
Fixed sanitize issue: missing copy in clones/duplicate methods, missing metricNameChanged method in metric_overrides_manager.ts called in html causing refresh not to be called properly upon update.
Fixed ${__cell...} multiple variables replacement, added unit test.

- #63 Missing metric name and value in polygon
Fixed auto-scale font

- #65 Auto Size option for Rows and Columns not always displaying all the hexagons
Fixed Automatic Columns/Rows count + automatic hexagon size

- #57 [Bug] zero Display Limit makes hexagons to disappear 
0 and empty values activate unlimited mode as specified by the tooltip + added hint for unlimited

### CODE REVIEW

**Comment by w4rgrum** [comment]
Should also fix #15 Use available panel space more efficiently

image

**Comment by w4rgrum** [comment]
Fixed some strange display on composites, ok for review

**Comment by rnovikovP** [comment]
@w4rgrum Thanks for the fix! 

@briangann is there any ETA on this PR and what a process to get this code to be on https://grafana.com/grafana/plugins/grafana-polystat-panel ? 

Thanks

**Comment by briangann** [comment]
will review today and merge, sorry for the delay, this is very cool!

**Comment by orena1** [comment]
Thanks @briangann, could you have a look at this please?

**Comment by infa-kparida** [comment]
Hi @briangann  Can we merge the changes.I am still facing the issue inpassing multiple varriables as mentioned in [ #58](https://github.com/grafana/grafana-polystat-panel/issues/58)

**Comment by ryantxu** [comment]
thanks @w4rgrum

**Pull request merged**
