### PR TITLE
Bugfix threshold for composites without override. Closes #158 and #173

### LINKED ISSUE #158: Color of composite doesn't equate the color of the most critical metric that compose it
I did a simple test with two queries (aliases A and B) returning one point each (A with the value 2, B with the value 0).

I created 3 thresholds:
  - 0 for OK (green)
  - 1 for WARNING (yellow)
  - 2 for CRITICAL (red)

This way I have two hexagons, one for A showing red with a value of 2, the other for B showing green with a value of 0.
Then I created a composite with the 2 metrics A and B. If I put first the metric A which has a "critical" value, the composite shows RED as expected :

grafana3

But if I put B which has a "OK" value, as the first metric of the composite, it shows GREEN: 

grafana

When hovering over the composite, the tooltip effectively shows the value of A and B:

grafana2

It seems that the color of the composite matches the color of its first metric, while I think it's expected that the color of the composite be the color of the highest threshold metric that compose it (red, for critical, in this case).

I tried with an elasticsearch data source and with an influxdb data source, both reproducing the issue.
Can someone else confirm this behaviour ? Is this expected behaviour or is it a bug ?

I ran grafana in a docker container with the following command: 
```bash
docker run -d \
-p 3000:3000 \
--name=grafana \
-e "GF_INSTALL_PLUGINS=grafana-polystat-panel" \
grafana/grafana
```

Grafana version : 7.2.1
grafana-polystat-panel version : 1.2.2

(also tried with grafana 6.7.3 and grafana-polystat-panel 1.2.1 with no success)

### PR DESCRIPTION
**Pull request by mjiderhamn**

### CODE REVIEW

**Comment by mjiderhamn** [comment]
While testing this I was seeing something odd: Threshold color `rgba(237, 129, 40, 1)` would not work for me (got all black), while `#e5ac0e` works just fine. If that is an actual issue and not just for me, then I suggest to address it separately, bug good to be aware of while testing.

**Comment by matletix** [comment]
> While testing this I was seeing something odd: Threshold color `rgba(237, 129, 40, 0.89)` would not work for me (got all black), while `#e5ac0e` works just fine. If that is an actual issue and not just for me, then I suggest to address it separately, bug good to be aware of while testing.

Agree with this. The default "warning" threshold color shows all black when gradients are enables (it displays fine for me when I disable gradients).

**Comment by matletix** [comment]
Fix #158
Fix #173

**Comment by briangann** [comment]
i've seen this yellow-state bug also - will open a separate pr for that, and review this one

**Review by briangann — APPROVED** [review]
works great!

**Pull request merged**
