### PR TITLE
Fix circles and rectangles creation when clickThroughURL is filled

### LINKED ISSUE #117: Adding URL to clickthrough causes to loosing cells color
Hi !

 When I add a  link (no matter where) to polystat's clickthrough and try to refresh all the cells, those with the link turn into dark state (they completely loose their color). Check it, please, out. We have the last Grafana update installed.

Thanks in advance
Andrii.

### LINKED ISSUE #154: Polystat circle or square shape with ClickThrough URL, drilldown does not work and fill color always black
Select shape as square\circle
The color coding is intact.
Give some click through URL, the squares and circles become black color.

This does not happen with Hexagons again.

Polystat- latest version (1.2.2)
Grafana 7

### PR DESCRIPTION
**Pull request by matletix**
Fix #154
Fix #117

### CODE REVIEW

**Comment by briangann** [comment]
testing this out, many thanks!

**Comment by briangann** [comment]
this looks like a partial fix, the square/rectangle is being fixed but only for the first one

image

image

**Comment by briangann** [comment]
have found the fix for the rest of this, will merge this change then put in another PR to patch it up.

**Comment by matletix** [comment]
Nice catch! Thanks

**Pull request merged**
