### PR TITLE
fix Polystats crashes on hover

### LINKED ISSUE #288: Polystat Crashes on Hover with Repeat Rows
# Issue
When hovering over a polystat panel that is repeated via a repeat row variable, the polystat panels in other rows crash.

## Before Hovering:
image
## After Hovering:
image
The admonition displays the following error: "Cannot read properties of undefined (reading 'color')"

image

Grafana Version: v10.0.1
Plugin Version: v2.1.0

### PR DESCRIPTION
**Pull request by Ukochka**
When hovering over a polystat panel that is repeated via a repeat row variable, the polystat panels in other rows crash.

It happened because data was undefined. I added optional chaining operator to avoid the crash

fixes #288

### CODE REVIEW

**Review by briangann — APPROVED** [review]
lgtm!

**Comment by TioVinaMatos** [comment]
Will it resolve the tooltip overlap as well? Faced this issue in version 2.1.2 of the plugin

image

**Comment by briangann** [comment]
> Will it resolve the tooltip overlap as well? Faced this issue in version 2.1.2 of the plugin
> 
> image

if it doesn't please open an issue so we can investigate it.  the tooltip replacement had unexpected side effects, i haven't seen that one happen. 

is that a leftover tooltip from within the same panel, or is it from a separate panel trying to follow the mouse?

**Comment by TioVinaMatos** [comment]
Thanks, I registered the issue: [https://github.com/grafana/grafana-polystat-panel/issues/315](315)

**Pull request merged**
