### PR TITLE
Changed default font from Roboto to Inter #258

### PR DESCRIPTION
**Pull request by beclerc**

### CODE REVIEW

**Comment by briangann** [comment]
will inspect this for v2.0.6, want to be sure we're not breaking older versions by making this change.

**Comment by beclerc** [comment]
> will inspect this for v2.0.6, want to be sure we're not breaking older versions by making this change.

Duely noted Brian, thank you !

**Comment by briangann** [comment]
I think a selector is needed, and ideally detect if the font is available, it definitely breaks older versions.

**Comment by beclerc** [comment]
Yes it would be better indeed. Did not think this would break older version ...

**Pull request closed without merging**
